services:
  kafka-ui:
    image: ${KAFKA_UI_IMAGE}
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: controller:9092
    networks:
      - kafka
    healthcheck:
      test: curl -s http://controller:9092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - controller

networks:
  kafka:
    external: true