version: '2'
services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - '${ELASTICSEARCH_PORT}:9200'
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      ELASTICSEARCH_PASSWORD: '${ELASTICSEARCH_PWD}'
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - elastic

networks:
  elastic:
    external: true